# Generated by Django 3.2.6 on 2021-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='ddffds', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
